# Regular expression to get the date from the filenames
date_re: \d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}

# Date format used in the filenames
date_format: "%Y-%m-%d_%H-%M-%S"

# Maximum days to keep files
max_days: 7

# Maximum size of all the files in bytes
max_size: 1e11

# Folder to monitor
files_path: /var/recordings

# List of file extensions to look for
file_extensions: [.mp4, .mkv]

# Seconds to wait before checking again
update_time: 3600